### ISSUE TITLE
Styling issues in Firefox 86.0b4

### ISSUE THREAD

**Issue by SanaRinomi** [groovy-bot/css-framework#16]
Site style completely unstable in Firefox, tried in multiple screen sizes.

![image](https://user-images.githubusercontent.com/16209282/106644441-6720e280-658b-11eb-8671-31b4dac0326f.png)

![image](https://user-images.githubusercontent.com/16209282/106644476-7142e100-658b-11eb-8c74-7f28ca42c242.png)

**Comment by rxsto** [comment]
Hey, thanks for reporting!

I seem to be unable to reproduce that issue. Could you paste a few details on your environment? (incl. OS, browser version etc.)

We also tend to get a few similar reports every now and then, and mostly it turns out that the user is using some extension that breaks the CSS on the site. 

Would appreciate if you could check the website in incognito as well.


Cheers,
rxsto

**Comment by SanaRinomi** [comment]
Yes, there does seem to be some extension influencing the site, as incognito mode shows a functional website. Though I'm reather curious as to know which extension is having an effect on the site as I've only had something like this happen on Groovy's site.
